SistemaEgresados/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/', include('api.urls')),

]

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('usuarios/', views.UsuarioList.as_view(), name='usuario-list'),
    path('usuarios/<int:pk>/', views.UsuarioDetail.as_view(), name='usuario-detail'),
    path('informacion-basica/', views.InformacionBasicaUsuarioList.as_view(), name='informacion-basica-list'),
    path('informacion-basica/<int:pk>/', views.InformacionBasicaUsuarioDetail.as_view(), name='informacion-basica-detail'),
    path('programas-upn/', views.ProgramasUPNList.as_view(), name='programas-upn-list'),
    path('programas-upn/<int:pk>/', views.ProgramasUPNDetail.as_view(), name='programas-upn-detail'),
    path('programas-externos/', views.ProgramasExternosList.as_view(), name='programas-externos-list'),
    path('programas-externos/<int:pk>/', views.ProgramasExternosDetail.as_view(), name='programas-externos-detail'),
    path('formacion-academica/', views.FormacionAcademicaList.as_view(), name='formacion-academica-list'),
    path('formacion-academica/<int:pk>/', views.FormacionAcademicaDetail.as_view(), name='formacion-academica-detail'),
]


core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.inicio, name="login"),
    path("salir/", views.salir, name="logout"),
    path("registro-egresado/", views.registro, name="registro-egresado"),
    path("registro-administrativo/", views.registro, name="registro-administrativo"),
    path("perfil/<int:id>", views.perfil, name="perfil"),
    path("informacion-basica/<int:id>", views.infoBasica, name="info-basica"),
    path("formacionUPN/", views.formacionUPN, name="formacionUPN"),
    path('get_programas', views.get_programas, name='get_programas'),
]

core/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator

import random
import string
from datetime import datetime


class Usuario(AbstractUser):
    username = models.CharField(max_length=20, unique=True)
    nombres = models.CharField(max_length=100)
    primer_apellido = models.CharField(max_length=50)
    segundo_apellido = models.CharField(max_length=50, blank=True, null=True)
    tipo_doc = models.CharField(max_length=20)
    documento = models.CharField(max_length=11)
    terminos = models.BooleanField(default=False)
    es_administrativo = models.BooleanField(default=False, blank=True)
    tipo_administrativo = models.CharField(max_length=100)
    facultad_administrativo = models.CharField(max_length=100)
    es_egresado = models.BooleanField(default=False, blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            # se usa timestamp + 5 numeros random para generar los ID
            timestamp = str(int(datetime.now().timestamp()))
            random_numbers = "".join(random.choices(string.digits, k=5))
            self.id = timestamp + random_numbers
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"
        db_table = "Usuario"


class InformacionBasicaUsuario(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    nombres = models.CharField(max_length=100)
    primer_apellido = models.CharField(max_length=50, default = "")
    segundo_apellido = models.CharField(max_length=50, blank=True, null=True)
    documento = models.CharField(max_length=11)
    sexo = models.CharField(max_length=20, default = "")
    grupo_etnico = models.CharField(max_length=50,  default = "")
    pais_nacimiento = models.CharField(max_length=100)
    depa_nacimiento = models.CharField(max_length=100, blank=True, null=True)
    mun_nacimiento = models.CharField(max_length=100, blank=True, null=True)    
    fecha_nacimiento = models.DateField(blank=True, null=True)
    estado_civil = models.CharField(max_length=50, default = "")
    discapacidad = models.CharField(max_length=100, blank=True, null=True)
    pais_res = models.CharField(max_length=100, default = "")
    depa_res = models.CharField(max_length=100, blank=True, null=True)
    mun_res = models.CharField(max_length=100, blank=True, null=True)
    direccion_residencia = models.CharField(max_length=100, blank=True)
    correo = models.EmailField()    
    correo_alternativo = models.EmailField(blank=True, null=True)
    telefono_principal = models.CharField(max_length=10, blank=True)
    telefono_alternativo = models.CharField(max_length=17, blank=True, null=True)

    def __str__(self):
        return f"{self.nombres} {self.primer_apellido}"  # Create your models here.

    class Meta:
        verbose_name = "Info Basica"
        verbose_name_plural = "Compilado Info"
        db_table = "Info Basica"


class ProgramasUPN(models.Model):
    programa = models.CharField(max_length=100)
    tipo_formacion = models.CharField(max_length=100)
    facultad = models.CharField(max_length=100)  # Nombre de la facultad
    titulo_obtenido = models.CharField(max_length=100)
    fecha_inicio = models.DateField(blank=True, null=True)
    fecha_fin = models.DateField(blank=True, null=True)  # Título que se obtiene al completar el programa

    def __str__(self):
        return f"{self.programa} - {self.titulo_obtenido}"

    class Meta:
        verbose_name = "Programa UPN"
        verbose_name_plural = "Programas UPN"
        db_table = "ProgramasUPN"


class UsuarioProgramasUPN(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    programa_upn = models.ForeignKey(ProgramasUPN, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Usuario Programa UPN"
        verbose_name_plural = "Usuarios Programas UPN"
        db_table = "UsuarioProgramasUPN"


class ProgramasExternos(models.Model):
    tipo_titulo = models.CharField(max_length=100)
    programa_externo = models.CharField(max_length=100)
    institucion = models.CharField(max_length=100)  # Nombre de la institución
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha_inicio = models.DateField(blank=True, null=True)
    fecha_fin = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.nombre_programa} - {self.tipo_titulo} - {self.institucion}"

    class Meta:
        verbose_name = "Programa Externo"
        verbose_name_plural = "Programas Externos"
        db_table = "ProgramasExternos"


class FormacionAcademica(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    programa_upn = models.ForeignKey(
        ProgramasUPN, on_delete=models.CASCADE, null=True, blank=True
    )
    programa_externo = models.ForeignKey(
        ProgramasExternos, on_delete=models.CASCADE, null=True, blank=True
    )
    fecha_inicio = models.DateField(blank=True, null=True)
    fecha_fin = models.DateField(blank=True, null=True)

    class Meta:
        verbose_name = "Formación Académica"
        verbose_name_plural = "Formaciones Académicas"
        db_table = "FormacionAcademica"

class ExperienciaLaboral(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha_inicio = models.DateField()
    fecha_finalizacion = models.DateField(null=True, blank=True)

    class Meta:
        abstract = True

class Docencia(ExperienciaLaboral):
    TIPO_INSTITUCION_CHOICES = [
        ('PUB', 'Pública'),
        ('PRI', 'Privada'),
        ('MIX', 'Mixta'),
    ]

    nombre_institucion = models.CharField(max_length=100)
    tipo_institucion = models.CharField(max_length=3, choices=TIPO_INSTITUCION_CHOICES)

class Cargo(models.Model):
    CARGO_CHOICES = [
        ('DIR', 'Directivo'),
        ('REC', 'Rector'),
        ('COO', 'Coordinador'),
        ('DOC', 'Docencia'),
        ('DIG', 'Dirección de grupo'),
        ('JEF', 'Jefatura de área'),
        ('CAP', 'Capacitación'),
        ('ASE', 'Asesoría pedagógica'),
        ('GES', 'Gestión de calidad'),
        ('DIS', 'Diseño de materiales'),
        ('INV', 'Investigación'),
        ('PAR', 'Participación en proyectos transversales'),
        ('NIV', 'Nivelación'),
        ('OTR', 'Otro'),
    ]

    docencia = models.ForeignKey(Docencia, on_delete=models.CASCADE)
    cargo = models.CharField(max_length=3, choices=CARGO_CHOICES)

class Editorial(ExperienciaLaboral):
    empresa_editorial = models.CharField(max_length=100)

class AsesorPedagogico(ExperienciaLaboral):
    institucion = models.CharField(max_length=100)

class ClasesParticulares(ExperienciaLaboral):
    pass

class DatosEmpleador(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    institucion = models.CharField(max_length=100)
    direccion_institucion = models.CharField(max_length=200)
    correo = models.EmailField()
    telefono_institucional = models.CharField(max_length=20)
    percepcion_egresado = models.TextField()

    def __str__(self):
        return self.nombre
    
class ProductividadAcademica(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

class Meta:
    abstract = True

class Libro(ProductividadAcademica):
    titulo = models.CharField(max_length=200)
    anio_publicacion = models.IntegerField()
    editorial = models.CharField(max_length=100)

class TextoEducativo(ProductividadAcademica):
    titulo = models.CharField(max_length=200)
    anio_publicacion = models.IntegerField()
    editorial = models.CharField(max_length=100)

class Articulo(ProductividadAcademica):
    titulo = models.CharField(max_length=200)
    anio_publicacion = models.IntegerField()
    revista = models.CharField(max_length=100)

class PonenciaEnMemoria(ProductividadAcademica):
    titulo = models.CharField(max_length=200)
    anio_publicacion = models.IntegerField()
    evento = models.CharField(max_length=100)
    ciudad_pais = models.CharField(max_length=100)

class AsistenciaEventosAcademicos(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nombre_evento = models.CharField(max_length=200)
    anio = models.IntegerField()
    tipo_participacion = models.CharField(max_length=50)
    ambito = models.CharField(max_length=50)
    organizadores = models.CharField(max_length=200)

class Investigacion(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    titulo_proyecto = models.CharField(max_length=200)
    anio_inicio = models.IntegerField()
    anio_finalizacion = models.IntegerField()
    grupo_investigacion = models.CharField(max_length=100)
    entidad_financiadora = models.CharField(max_length=100)

class ReconocimientosAcademicos(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    tipo_reconocimiento = models.CharField(max_length=100)
    quien_otorga = models.CharField(max_length=100)
    anio = models.IntegerField()

class ParticipacionEnRedes(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nombre_red = models.CharField(max_length=100)
    anio_inicio = models.IntegerField()
    anio_finalizacion = models.IntegerField()

class ParticipacionEnOrganizaciones(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nombre_organizacion = models.CharField(max_length=100)
    tipo_organizacion = models.CharField(max_length=50)
    funcion_organizacion = models.CharField(max_length=100)
    anio_inicio = models.IntegerField()

core/project_management/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Proyecto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    tipo_proyecto = models.CharField(max_length=50)
    administrador = models.ForeignKey(User, on_delete=models.CASCADE, related_name='proyectos_administrados')
    miembros = models.ManyToManyField(User, related_name='proyectos_miembro')

class Tarea(models.Model):
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, related_name='tareas')
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    asignado_a = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tareas_asignadas')

class Cronograma(models.Model):
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, related_name='cronogramas')
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()

# Create your models here.

core/project_management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Proyecto, Tarea, Cronograma
from .forms import ProyectoForm, TareaForm, CronogramaForm

def lista_proyectos(request):
    proyectos = Proyecto.objects.all()
    return render(request, 'proyectos/lista_proyectos.html', {'proyectos': proyectos})

def detalle_proyecto(request, proyecto_id):
    proyecto = get_object_or_404(Proyecto, id=proyecto_id)
    return render(request, 'proyectos/detalle_proyecto.html', {'proyecto': proyecto})

def crear_proyecto(request):
    if request.method == 'POST':
        form = ProyectoForm(request.POST)
        if form.is_valid():
            proyecto = form.save(commit=False)
            proyecto.administrador = request.user
            proyecto.save()
            return redirect('lista_proyectos')
    else:
        form = ProyectoForm()
    return render(request, 'proyectos/crear_proyecto.html', {'form': form})

def agregar_miembro(request, proyecto_id):
    proyecto = get_object_or_404(Proyecto, id=proyecto_id)
    if request.method == 'POST':
        usuario_id = request.POST.get('usuario_id')
        usuario = get_object_or_404(User, id=usuario_id)
        proyecto.miembros.add(usuario)
        return redirect('detalle_proyecto', proyecto_id=proyecto.id)
    return render(request, 'proyectos/agregar_miembro.html', {'proyecto': proyecto})

def crear_tarea(request, proyecto_id):
    proyecto = get_object_or_404(Proyecto, id=proyecto_id)
    if request.method == 'POST':
        form = TareaForm(request.POST)
        if form.is_valid():
            tarea = form.save(commit=False)
            tarea.proyecto = proyecto
            tarea.save()
            return redirect('detalle_proyecto', proyecto_id=proyecto.id)
    else:
        form = TareaForm()
    return render(request, 'proyectos/crear_tarea.html', {'form': form, 'proyecto': proyecto})

def crear_cronograma(request, proyecto_id):
    proyecto = get_object_or_404(Proyecto, id=proyecto_id)
    if request.method == 'POST':
        form = CronogramaForm(request.POST)
        if form.is_valid():
            cronograma = form.save(commit=False)
            cronograma.proyecto = proyecto
            cronograma.save()
            return redirect('detalle_proyecto', proyecto_id=proyecto.id)
    else:
        form = CronogramaForm()
    return render(request, 'proyectos/crear_cronograma.html', {'form': form, 'proyecto': proyecto})

# Create your views here.

core/templates/core/asistencia_eventos_academicos.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <h1>Asistencia a Eventos Académicos</h1>
  
  <ul>
    {% for asistencia in asistencias %}
      <li>
        <strong>Nombre Evento:</strong> {{ asistencia.nombre_evento }}<br>
        <strong>Año:</strong> {{ asistencia.anio }}<br>
        <strong>Tipo Participación:</strong> {{ asistencia.tipo_participacion }}<br>
        <strong>Ámbito:</strong> {{ asistencia.ambito }}<br>
        <strong>Organizadores:</strong> {{ asistencia.organizadores }}
      </li>
    {% empty %}
      <li>No hay registros de asistencia a eventos académicos.</li>
    {% endfor %}
  </ul>
  
  <h3>Agregar Asistencia a Evento Académico</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
</div>
{% endblock %}

core/templates/core/formacionUPN.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

<div class="card card-primary card-outline">
    <div class="card-header">
        <h5 class="m-0">Formación Académica</h5>
    </div>

<div class="card card-default">
    <form method="post" action="{% url 'formacionUPN' %}">
        {% csrf_token %}
        <div class="row">
            <!-- Columna Izquierda -->
            <div class="col-md-6">
                <!-- Tipo de Formación -->
                <div class="form-group">
                    <label for="id_tipo_formacion">Tipo de Formación*</label>
                    {{ form.tipo_formacion|add_class:"form-control"|add_error_class:"error-field" }}
                </div>
    
                <!-- Facultad -->
                <div class="form-group">
                    <label for="id_facultad">Facultad*</label>
                    {{ form.facultad|add_class:"form-control"|add_error_class:"error-field" }}
                </div>
    
                <!-- Programa -->
                <div class="form-group">
                    <label for="id_programa">Programa*</label>
                    {{ form.programa|add_class:"form-control"|add_error_class:"error-field" }}
                </div>
            </div>
    
            <!-- Columna Derecha -->
            <div class="col-md-6">
   
                <!-- Fecha de Inicio -->
                <label for="id_fecha_inicio">Fecha de Inicio*</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                    </div>
                    {{ form.fecha_inicio|add_class:"form-control datepicker"|add_error_class:"error-field" }}
                </div>
    
                <!-- Fecha de Fin -->
                <label for="id_fecha_fin">Fecha de Fin</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                    </div>
                    {{ form.fecha_fin|add_class:"form-control datepicker"|add_error_class:"error-field" }}
                </div>
                <!-- Título Obtenido -->
                <div class="form-group">
                    <label for="id_titulo_obtenido">Título Obtenido*</label>
                    {{ form.titulo_obtenido|add_class:"form-control"|add_error_class:"error-field" }}
                </div>
            </div>
        </div>
    
        <div class="modal-footer justify-content-between">
            <div class="text-right">
                <button type="submit" class="btn btn-primary">Guardar Cambios</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

core/templates/core/formy.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

 

{% endblock %}

core/templates/core/index.html
{% load static %}

<!-- Default box -->

  <style>
    .centrado {
      text-align: center;
      display: flex;
      flex-direction: column;
      align-items: center;
    }
  </style>
  {% if user.is_authenticated %}
  <script type="text/javascript">
    window.location.href = "{% url 'perfil' user.id %}";
</script>
  {% else%}
  <div class="card-body">
    <!-- Aca va las cards a mostrar  -->
    <div class="card card-primary card-outline">
      <div class="card-header">
        <h4 class="m-0">Bienvenido</h4>
      </div>
      <div class="card-body centrado">
        <img src="{% static 'images/logo-blue.png' %}" alt="Logo" style="max-width: 250px; margin-bottom: 30px; margin-left: -10px; ">        
        
        <h2 class="card-title" style="font-weight: bold; color: rgb(37, 150, 190);">Este es el módulo de pruebas del Sistema de Información de Egresados</h2>
        <br>
        <div>
          <a href="{% url 'login' %}" class="btn btn-success mr-2"><i class="fas fa-sign-in-alt"></i> Iniciar Sesión</a>
          <a href="{% url 'registro-egresado' %}" class="btn btn-primary mr-2"><i class="fas fa-user-plus"></i> Registro Egresados</a>
          <a href="{% url 'registro-administrativo' %}" class="btn btn-info"><i class="fas fa-user-cog"></i> Registro Administrativos</a>
        </div>
      </div>
    </div>
  </div>
  <!-- /.card-body -->
  {% endif %}
</div>
<!-- /.card -->

core/templates/core/info-basica2.html
{% extends 'core/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

<style>
    .datepicker-container {
        z-index: 1051;
    }
    /* Más estilos aquí si es necesario */
</style>

<!-- Default box -->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-9"> <!-- Ajusta el ancho aquí según tus necesidades -->
            <div class="card">
                <div class="card-body box-profile">
                    <div class="d-flex align-items-start">
                        <div>
                            <a class="btn btn-success mr-2" data-toggle="modal" data-target="#personalDataModal"><i
                                    class="fas fa-sign-in-alt"></i> Editar II </a>                                   
                        </div>                     
                    </div>
                    </ul>
                </div>
                <!-- /.card-body -->
<!-- Fecha de Nacimiento -->
<div class="form-group">
    <label for="id_documento">Fecha Nacimiento</label>
    <div class="input-group date" id="reservationdate" data-target-input="nearest">
        <input type="text" id="datemask" class="form-control datetimepicker-input" 
               data-target="#reservationdate" 
               readonly 
               placeholder="dd/mm/yyyy"/>
        <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
        </div>
    </div>
</div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="personalDataModal" role="dialog">
    <div class="modal-dialog modal-lg"> <!-- Aquí se hace el modal más ancho -->
        <div class="modal-content">
            <div class="modal-header">
                <b>
                    <h6 class="modal-title">Formulario Datos Personales</h6>
                </b>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'info-basica' usuario.id %}">
                    {% csrf_token %}
                    <div class="card-body">
                        <!-- Nombres -->
                        <label for="id_nombres">Nombres</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-user"></i></span>
                            </div>
                            {{ form.nombres }}
                        </div>
                        <!-- Apellidos -->
                        <label for="id_apellidos">Apellidos</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-user"></i></span>
                            </div>
                            {{ form.apellidos }}
                        </div>
                        <!-- Documento -->
                        <label for="id_documento">Documento</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-id-card"></i></span>
                            </div>
                            {{ form.documento }}
                        </div>
                        <!-- Fecha de Nacimiento -->
                        <div class="form-group">
                            <label for="id_documento">Fecha de Nacimiento </label>
                              <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                  <input type="text" class="form-control datetimepicker-input" data-target="#reservationdate" readonly placeholder="Presione botón"/>
                                  <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                      <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                  </div>
                              </div>
                          </div>
                        <!-- Correo Personal -->
                        <label for="id_correo_personal">Correo Personal</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                            </div>
                            {{ form.correo_personal }}
                        </div>
                        <!-- Correo Alternativo -->
                        <label for="id_correo_alternativo">Correo Alternativo</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-envelope-open"></i></span>
                            </div>
                            {{ form.correo_alternativo }}
                        </div>
                        <!-- Correo Institucional -->
                        <label for="id_correo_institucional">Correo Institucional</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-university"></i></span>
                            </div>
                            {{ form.correo_institucional }}
                        </div>
                        <!-- Dirección de Residencia -->
                        <label for="id_direccion_residencia">Dirección de Residencia</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-home"></i></span>
                            </div>
                            {{ form.direccion_residencia }}
                        </div>
                        <!-- Barrio -->
                        <label for="id_barrio">Barrio</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-building"></i></span>
                            </div>
                            {{ form.barrio }}
                        </div>
                        <!-- Ciudad -->
                        <label for="id_ciudad">Ciudad</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-city"></i></span>
                            </div>
                            {{ form.ciudad }}
                        </div>
                        <!-- País -->
                        <label for="id_pais">País</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-flag"></i></span>
                            </div>
                            {{ form.pais }}
                        </div>
                        <!-- Teléfono Móvil -->
                        <label for="id_telefono_movil">Teléfono Móvil</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-mobile-alt"></i></span>
                            </div>
                            {{ form.telefono_movil }}
                        </div>
                        <!-- Teléfono Alternativo -->
                        <label for="id_telefono_alternativo">Teléfono Alternativo</label>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-phone"></i></span>
                            </div>
                            {{ form.telefono_alternativo }}
                        </div>
                        <!-- Botón de envío -->
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        <div class="text-right"> <!-- Alineación a la derecha para el botón de envío -->
                            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>

<script>

    $(document).ready(function() {
        $('#personalDataModal').on('shown.bs.modal', function () {
            $('#reservationdate').datetimepicker({
                format: 'L'
            });
        });
    });


    $(document).ready(function(){
    // Aplicar Inputmask a tu campo de datepicker
    $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' });

    // Inicializar el datepicker
    $('#reservationdate').datetimepicker({
        format: 'L'
        // ... otras opciones de configuración si son necesarias
    });
});
    </script>

    


{% endblock %}